"use client";

import type { MortgageFileFields } from "@/types/document";
import { ApplicationFunnelChart } from "@/components/mortgage-charts/ApplicationFunnelChart";
import { BorrowerCurrencyDistributionChart } from "@/components/mortgage-charts/BorrowerCurrencyDistributionChart";
import { BorrowerSegmentMixChart } from "@/components/mortgage-charts/BorrowerSegmentMixChart";
import { DebtToIncomeDistributionChart } from "@/components/mortgage-charts/DebtToIncomeDistributionChart";
import { DelinquencyRateChart } from "@/components/mortgage-charts/DelinquencyRateChart";
import { DocumentTurnaroundTimeChart } from "@/components/mortgage-charts/DocumentTurnaroundTimeChart";
import { DTILTVScatterChart } from "@/components/mortgage-charts/DTILTVScatterChart";
import { FieldAccuracyHeatMapChart } from "@/components/mortgage-charts/FieldAccuracyHeatMapChart";
import { IDDocumentExpiryHeatMapChart } from "@/components/mortgage-charts/IDDocumentExpiryHeatMapChart";
import IncomeDiscrepancyChart from "@/components/mortgage-charts/IncomeDiscrepancyChart";
import { LoanToValueDistributionChart } from "@/components/mortgage-charts/LoanToValueDistributionChart";
import { MissingDocsChart } from "@/components/mortgage-charts/MissingDocsChart";
import { PropertyGeoDistributionChart } from "@/components/mortgage-charts/PropertyGeoDistributionChart";
import { PropertyTypeDistributionChart } from "@/components/mortgage-charts/PropertyTypeDistributionChart";
import { UnderwritingCycleTimeChart } from "@/components/mortgage-charts/UnderwritingCycleTimeChart";
import { WeeklyApplicationVolumeChart } from "@/components/mortgage-charts/WeeklyApplicationVolumeChart";
import {
	makeDashboardItemUuid,
	makeDashboardProjectUuid,
} from "@/helpers/utils";
import { ChartType } from "@/types/general-enums";
import {
	createISODate,
	createMessageUuid,
	type Message,
} from "@/types/organization";
import type { DashboardProject } from "@/contexts/luminaStore";

export const FAKE_MORTGAGE_FILES: Array<
	[filename: string, fields: MortgageFileFields, chatMessages: Array<Message>]
> = [
	[
		"Appraisal_Fee_Official_Receipt.pdf",
		{
			file_name: "Appraisal_Fee_Official_Receipt.pdf",
			document_type: "appraisal_fee_payment_receipt",
			receipt_number: "2861427",
			payer_name: "Juan Dela Cruz",
			payee_name: "Dixon Farm Appraisal Services",
			amount_paid: 3500.0,
			date_paid: "2025-01-08",
			payment_method: null,
		},
		[
			{
				text: "The Appraisal Fee Receipt is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				showSender: true,
				toggleText: "",
			},
		],
	],
	[
		"Payroll_Bank_Statement_January_2025.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2025-01-01",
			credit_amount: 33487.5,
			running_balance: 166806.5,
		},
		[
			{
				text: "The January 2025 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Appraisal_Report_Townhouse_Taguig.pdf",
		{
			file_name: "Appraisal_Report_Townhouse_Taguig.pdf",
			document_type: "appraisal_report",
			appraised_market_value: 3590147.0,
			forced_sale_value: 2872117.6,
			valuation_methodology: "Market Comparison Approach",
			appraiser_name: "Engr. Liza Mendoza",
			appraisal_date: "2025-01-10",
			property_address: "Taguig City, Metro Manila",
		},
		[
			{
				text: "The appraisal report for the Taguig townhouse is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_March_2025.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2025-01-16",
			credit_amount: 36287.5,
			running_balance: 171461.0,
		},
		[
			{
				text: "The March 2025 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Authorization_Letter_Employment_Bank_Verification.pdf",
		{
			file_name: "Authorization_Letter_Employment_Bank_Verification.pdf",
			document_type: "authorization_letter",
			authorizer_full_name: "Juan Dela Cruz",
			authorizee_full_name:
				"Relevant financial institution, employer, or designated third-party service provider",
			authorization_purpose:
				"Verification of employment and banking information for processing a mortgage loan application",
			date_issued: "2025-01-03",
			contact_number: null,
			validity_end_date: null,
		},
		[
			{
				text: "The authorization letter for employment and bank verification is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_November_2024.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2025-02-01",
			credit_amount: 33487.5,
			running_balance: 180724.5,
		},
		[
			{
				text: "The November 2024 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"BIR_Form_2316_Juan_Dela_Cruz.pdf",
		{
			file_name: "BIR_Form_2316_Juan_Dela_Cruz.pdf",
			document_type: "bir_form_2316",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			employer_tin: "135-246-357-0000",
			taxable_year: null,
			gross_compensation_income: 1165000.0,
			taxable_income: 1020000.0,
			tax_withheld: 157500.0,
		},
		[
			{
				text: "BIR Form 2316 for Juan Dela Cruz is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_Apr1_15.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_Apr1_15.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-04-01",
			pay_period_end: "2025-04-15",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 9212.5,
			net_pay: 33487.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (April 1-15) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_Apr16_30.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_Apr16_30.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-04-16",
			pay_period_end: "2025-04-30",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 6212.5,
			net_pay: 36287.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (April 16-30) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				toggleText: "",
				showFooter: true,
				showSender: true,
			},
		],
	],
	[
		"BIR TIN.pdf",
		{
			file_name: "BIR TIN.pdf",
			document_type: "tin_card",
			tin: "123-456-789-0000",
			full_name: "JUAN DELA CRUZ",
			issue_date: "2020-01-03",
		},
		[
			{
				text: "The BIR TIN card is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_Feb16_28.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_Feb16_28.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-02-16",
			pay_period_end: "2025-02-28",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 6212.5,
			net_pay: 36287.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (February 16-28) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Building_Permit_Bill_of_Materials_Taguig.pdf",
		{
			file_name: "Building_Permit_Bill_of_Materials_Taguig.pdf",
			document_type: "building_permit",
			permit_number: "BP-24405",
			project_name: "Building Permit & Bill of Materials",
			project_location:
				"123 Acacia Lane, Brgy. Ususan, Taguig City, Metro Manila",
			owner_full_name: "Juan Dela Cruz",
			contractor_name: null,
			estimated_cost: 1200000.0,
			date_issued: "2025-01-06",
			expiry_date: null,
		},
		[
			{
				text: "The building permit and bill of materials for Taguig is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				toggleText: "",
				showFooter: true,
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_Mar1_15.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_Mar1_15.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-03-01",
			pay_period_end: "2025-03-15",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 9212.5,
			net_pay: 33487.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (March 1-15) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Certificate_of_Employment_Dixon_Farm.pdf",
		{
			file_name: "Certificate_of_Employment_Dixon_Farm.pdf",
			document_type: "certificate_of_employment_and_compensation",
			employer_name: "Dixon Farm",
			employee_full_name: "Juan Dela Cruz",
			position: "Accountant",
			employment_start_date: "2011-01-01",
			gross_monthly_income: 85000.0,
			gross_annual_income: 1020000.0,
			signatory_name: "Emmanuel Reyes",
			date_issued: "2025-04-05",
		},
		[
			{
				text: "The Certificate of Employment from Dixon Farm is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				toggleText: "",
				showFooter: true,
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_Mar16_31.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_Mar16_31.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-03-16",
			pay_period_end: "2025-03-31",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 6212.5,
			net_pay: 36287.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (March 16-31) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				toggleText: "",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				showSender: true,
			},
		],
	],
	[
		"CIC_Credit_Report_Juan_Dela_Cruz.pdf",
		{
			file_name: "CIC_Credit_Report_Juan_Dela_Cruz.pdf",
			document_type: "cic_report",
			report_date: null,
			cic_score: 762,
			delinquency_flags: "None",
			number_active_trade_lines: 3,
		},
		[
			{
				text: "The CIC Credit Report for Juan Dela Cruz is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payslip_Juan_Dela_Cruz_May1_15.pdf",
		{
			file_name: "Payslip_Juan_Dela_Cruz_May1_15.pdf",
			document_type: "payslip",
			employee_full_name: "Juan Dela Cruz",
			employer_name: "Dixon Farm",
			pay_period_start: "2025-05-01",
			pay_period_end: "2025-05-15",
			basic_pay: 40000.0,
			allowances: 2500.0,
			overtime_pay: 0.0,
			deductions_total: 9212.5,
			net_pay: 33487.5,
		},
		[
			{
				text: "Payslip for Juan Dela Cruz (May 1-15) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Deed_of_Absolute_Sale_Townhouse_Taguig.pdf",
		{
			file_name: "Deed_of_Absolute_Sale_Townhouse_Taguig.pdf",
			document_type: "deed_of_absolute_sale",
			buyer_name: "Juan Dela Cruz",
			seller_name: "Maria Santos",
			consideration_amount: 3590147.0,
			date_of_execution: "2025-01-15",
			notary_name: "Atty. Roberto Dela Peña",
			notary_doc_number: null,
			property_description:
				"A residential townhouse located at 123 Acacia Lane, Brgy. Ususan, Taguig City, Metro Manila, with a total lot area of 82 square meters and registered under Transfer Certificate of Title No. T-196862",
		},
		[
			{
				text: "The Deed of Absolute Sale for the Taguig townhouse is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Personal_Loan_Statement_April_2025.pdf",
		{
			file_name: "Personal_Loan_Statement_April_2025.pdf",
			document_type: "personal_loan_statement",
			statement_date: "2025-04-01",
			account_number_masked: null,
			lender_name: null,
			credit_limit: 100000.0,
			outstanding_balance: 31633.0,
			minimum_payment_due: 5000.0,
			payment_due_date: null,
			last_payment_amount: null,
		},
		[
			{
				text: "The personal loan statement for April 2025 is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Lot_Building_Plan_Vicinity_Map_Townhouse_Taguig.pdf",
		{
			file_name: "Lot_Building_Plan_Vicinity_Map_Townhouse_Taguig.pdf",
			document_type: "lot_building_plan_vicinity_map",
			survey_number: "PLS-8615",
			technical_description:
				"A parcel of land (Lot 12, Blk 7, Unit B), situated in the Brgy. Ususan, Taguig City, bounded on the NW by Lot 11, on the NE by a road lot, on the SE by Lot 13, and on the SW by Lot 8. Containing an area of 82 square meters, more or less.",
			scale: "1:500",
			engineer_name: "Engr. Maria Luisa Flores",
			engineer_license_number: null,
			date_prepared: null,
		},
		[
			{
				text: "The lot building plan and vicinity map for the Taguig townhouse is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Philsys.pdf",
		{
			file_name: "Philsys.pdf",
			document_type: "government_issued_id",
			id_type: "Philippine Identification Card (PhilSys ID)",
			full_name: "JUAN MARTINEZ DELA CRUZ",
			id_number: "1234-5678-9101-1213",
			birthdate: "1990-01-01",
			address:
				"833 SISA ST., BRGY 526, ZONE 52 SAMPALOK, MANILA CITY, METRO MANILA",
			issue_date: "2019-06-14",
			expiry_date: null,
			issuing_authority: "Philippine Statistics Authority (PSA)",
		},
		[
			{
				text: "The PhilSys ID for Juan Martinez Dela Cruz is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Marriage Cert.pdf",
		{
			file_name: "Marriage Cert.pdf",
			document_type: "marriage_certificate",
			spouse1_full_name: "JUAN DELA CRUZ",
			spouse2_full_name: "MARIA PEREZ",
			date_of_marriage: "2018-04-08",
			place_of_marriage: "ST JOSEPH CHURCH, TONDO, METRO MANILA",
			registry_number: "206-167",
		},
		[
			{
				text: "The Marriage Certificate for Juan Dela Cruz and Maria Perez is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Mortgage_Loan_Application_Form_Juan_Dela_Cruz_IncomeFixed.pdf",
		{
			file_name:
				"Mortgage_Loan_Application_Form_Juan_Dela_Cruz_IncomeFixed.pdf",
			document_type: "loan_application_form",
			loan_type: "Home Purchase",
			loan_amount: 2390755,
			loan_term_months: 240,
			loan_purpose: "Buy a new house and lot",
			borrower_full_name: "Juan Dela Cruz",
			borrower_birthdate: "1990-01-01",
			borrower_civil_status: null,
			borrower_address:
				"833 Sisa St. Brgy 526 Zone 52, Sampaloc, Manila City, Metro Manila",
			borrower_contact_number: null,
			co_borrower_full_name: "Ernesto Manalaysay",
			co_borrower_relationship: "Brother in Law",
			employer_name: "Dixon Farm",
			employer_address: "123 San Jose Del Monte, Bulacan",
			employment_status: "Accountant",
			employment_start_date: null,
			declared_gross_monthly_income: 85000,
			declared_other_income: null,
			declared_existing_debts: 31633,
			declared_monthly_expenses: 23078,
			collateral_property_type: "Townhouse",
			collateral_property_address: "Taguig City",
			collateral_estimated_value: 3590147,
		},
		[
			{
				text: "The Mortgage Loan Application Form for Juan Dela Cruz is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"RPT_Receipt_Townhouse_Taguig.pdf",
		{
			file_name: "RPT_Receipt_Townhouse_Taguig.pdf",
			document_type: "real_property_tax_receipt",
			receipt_number: "3400154",
			tax_year: 2025,
			amount_paid: 24000.0,
			date_paid: "2025-01-25",
		},
		[
			{
				text: "The Real Property Tax Receipt for the Taguig townhouse is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Special_Power_of_Attorney_Juan_Dela_Cruz.pdf",
		{
			file_name: "Special_Power_of_Attorney_Juan_Dela_Cruz.pdf",
			document_type: "special_power_of_attorney",
			principal_full_name: "Juan Dela Cruz",
			attorney_in_fact_full_name: "Ernesto Manalaysay",
			scope_of_authority:
				"To act for and on behalf of the Principal in the execution and signing of all necessary documents pertaining to the sale, mortgage, and transfer of the townhouse property located in Taguig City, Metro Manila, including dealings with the Registry of Deeds, BIR, and other government agencies or private institutions.",
			date_of_execution: "2025-01-05",
			notary_name: null,
			notary_doc_number: null,
			validity_end_date: null,
		},
		[
			{
				text: "The Special Power of Attorney for Juan Dela Cruz is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_April_2025.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2024-12-16",
			credit_amount: 36287.5,
			running_balance: 156604.0,
		},
		[
			{
				text: "The April 2025 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Tax_Declaration_Townhouse_Taguig.pdf",
		{
			file_name: "Tax_Declaration_Townhouse_Taguig.pdf",
			document_type: "tax_declaration",
			property_index_number: "7505163061",
			owner_name: "Juan Dela Cruz",
			assessed_value_land: 900000.0,
			assessed_value_building: 1500000.0,
			property_classification: "Residential",
			arp_year: 2025,
		},
		[
			{
				text: "The Tax Declaration for the Taguig townhouse is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2024-11-01",
			credit_amount: 33487.5,
			running_balance: 138487.5,
		},
		[
			{
				text: "The consolidated payroll bank statement (Nov-Apr) is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Transfer_Certificate_of_Title_Taguig.pdf",
		{
			file_name: "Transfer_Certificate_of_Title_Taguig.pdf",
			document_type: "transfer_certificate_of_title",
			title_number: "T-991053",
			registry_of_deeds: "Registry of Deeds for Taguig City",
			lot_block_unit: "Lot 12, Blk 7, Unit B",
			area_sqm: 82,
			registered_owner: "Juan Dela Cruz",
			encumbrances: "None",
		},
		[
			{
				text: "The Transfer Certificate of Title for the Taguig property is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_December_2024.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2024-11-16",
			credit_amount: 36287.5,
			running_balance: 143124.0,
		},
		[
			{
				text: "The December 2024 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"Payroll_Bank_Statement_February_2025.pdf",
		{
			file_name: "Payroll_Bank_Statement_Consolidated_Nov-Apr.pdf",
			document_type: "payroll_bank_statement",
			bank_name: "MetroBank",
			account_number_masked: "****-****-1234",
			transaction_date: "2024-12-01",
			credit_amount: 33487.5,
			running_balance: 151949.5,
		},
		[
			{
				text: "The February 2025 payroll bank statement is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
	[
		"UtilityBill.pdf",
		{
			file_name: "UtilityBill.pdf",
			document_type: "proof_of_billing",
			customer_name: "JUAN DELA CRUZ",
			account_number: "16800001234",
			service_provider:
				"Converge Information and Communications Technology Solutions, Inc.",
			service_address:
				"833 Sisa St. Brgy 526 Zone 52, Sampaloc, Manila City, Metro Manila 1008",
			billing_period_start: "2025-05-01",
			billing_period_end: "2025-05-31",
			amount_due: 2625.0,
		},
		[
			{
				text: "The Utility Bill is ready for review.",
				createdAt: createISODate(),
				uuid: createMessageUuid(),
				sender: "bot",
				statuses: [{ status: "streaming" }, { status: "success" }],
				statusIndex: 0,
				showFooter: true,
				toggleText: "",
				showSender: true,
			},
		],
	],
] as const;

export const FAKE_MORTGAGE_DASHBOARD_CHARTS: Array<DashboardProject> = [
	{
		uuid: makeDashboardProjectUuid(),
		name: "Pipeline Health",
		items: [
			{
				description: "Intake -> KYC -> Underwriting -> Approved -> Booked",
				chart: ApplicationFunnelChart,
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Stacked,
				name: "Application Funnel",
				chartConfig: {},
				data: [],
			},
			{
				chart: WeeklyApplicationVolumeChart,
				name: "Weekly Application Volume",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Line,
				description: "",
				chartConfig: {},
				data: [],
			},
			{
				description: "Employed, Self-employed, OFW, Professionals",
				chart: BorrowerSegmentMixChart,
				uuid: makeDashboardItemUuid(),
				name: "Borrower Segment Mix",
				chartType: ChartType.Stacked,
				chartConfig: {},
				data: [],
			},
		],
	},
	{
		name: "Risk & Compliance Snapshot",
		uuid: makeDashboardProjectUuid(),
		items: [
			{
				description: "With 30% & 40% guideline bands",
				name: "Debt-to-Income (DTI) distribution",
				chart: DebtToIncomeDistributionChart,
				chartType: ChartType.Histogram,
				uuid: makeDashboardItemUuid(),
				chartConfig: {},
				data: [],
			},
			{
				name: "Loan-to-Value (LTV) distribution",
				chart: LoanToValueDistributionChart,
				description: "With 80% / 90% caps",
				chartType: ChartType.Histogram,
				uuid: makeDashboardItemUuid(),
				chartConfig: {},
				data: [],
			},
			{
				description:
					"Debt-to-Income (DTI) vs Loan-to-Value (LTV) distribution with guideline quadrants.",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Scatter,
				chart: DTILTVScatterChart,
				name: "DTI vs. LTV",
				chartConfig: {},
				data: [],
			},
			{
				description: "Days to expiry by application",
				chart: IDDocumentExpiryHeatMapChart,
				uuid: makeDashboardItemUuid(),
				name: "ID / document expiry",
				chartType: ChartType.Area,
				chartConfig: {},
				data: [],
			},
			{
				description:
					"Extracted Income vs. Declared Income Discrepancy with 0% and 5% Thresholds.",
				name: "Extracted-vs-declared income discrepancy",
				chart: IncomeDiscrepancyChart,
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.BoxPlot,
				chartConfig: {},
				data: [],
			},
		],
	},
	{
		name: "Portfolio & Collateral Analytics",
		uuid: makeDashboardProjectUuid(),
		items: [
			{
				description: "Loan amount by province/city",
				chart: PropertyGeoDistributionChart,
				name: "Property geo-distribution",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.BoxPlot,
				chartConfig: {},
				data: [],
			},
			{
				description: "House & lot/Condo/Vacant lot",
				name: "Average LTV by property type",
				chart: PropertyTypeDistributionChart,
				chartType: ChartType.GroupedBarChart,
				uuid: makeDashboardItemUuid(),
				chartConfig: {},
				data: [],
			},
			{
				chart: BorrowerCurrencyDistributionChart,
				name: "Exposure by borrower currency",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Donut,
				description: "For OFWS",
				chartConfig: {},
				data: [],
			},
			{
				description: "30-day-delinquency rate vs. booking month",
				uuid: makeDashboardItemUuid(),
				chart: DelinquencyRateChart,
				chartType: ChartType.Line,
				name: "Vintage analysis",
				chartConfig: {},
				data: [],
			},
		],
	},
	{
		name: "Operational Efficiency Metrics",
		uuid: makeDashboardProjectUuid(),
		items: [
			{
				name: "Average document-turnaround time",
				chart: DocumentTurnaroundTimeChart,
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.BoxPlot,
				description: "Per doc type",
				chartConfig: {},
				data: [],
			},
			{
				name: "% Applications with missing docs",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Line,
				chart: MissingDocsChart,
				chartConfig: {},
				description: "",
				data: [],
			},
			{
				description: "Received -> Approval",
				chart: UnderwritingCycleTimeChart,
				name: "Underwriting cycle time",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Line,
				chartConfig: {},
				data: [],
			},
			{
				description: "Field-level accuracy heat-map",
				chart: FieldAccuracyHeatMapChart,
				name: "Top OCR error sources",
				uuid: makeDashboardItemUuid(),
				chartType: ChartType.Line,
				chartConfig: {},
				data: [],
			},
		],
	},
];
