export const COMMISSION_FILE_METADATA_STEPS = {
	currentCategory: -1,
	currentStep: 1,
	categories: [],
	steps: [
		{
			step: 1,
			description: "",
			title: "Field Validation",
			isCompleted: true,
			isAutomated: false,
			currentSubStep: -1,
			dealsWithSubFiles: true,
		},
		{
			step: 2,
			description: "",
			title: "Information Completeness",
			isCompleted: true,
			isAutomated: false,
			currentSubStep: -1,
			dealsWithSubFiles: false,
		},
		{
			step: 3,
			description: "",
			title: "Calculate Commision",
			isCompleted: false,
			isAutomated: true,
			currentSubStep: 3,
			dealsWithSubFiles: false,
		},
		{
			step: 4,
			description: "",
			title: "Ask for Approval",
			isCompleted: false,
			isAutomated: true,
			currentSubStep: 3,
			dealsWithSubFiles: false,
			subSteps: [
				{
					step: 1,
					description: "",
					title: "Email to finance department",
					isCompleted: false,
					isAutomated: true,
					currentSubStep: -1,
					dealsWithSubFiles: false,
				},
				{
					step: 2,
					description: "",
					title: "Add to ERP system",
					isCompleted: false,
					isAutomated: true,
					currentSubStep: -1,
					dealsWithSubFiles: false,
				},
			],
		},
	],
};
