export const MORTGAGE_FILE_METADATA_STEPS = {
	currentCategory: -1,
	currentStep: 1,
	categories: [],
	steps: [
		{
			step: 1,
			description: "",
			title: "Field Validation",
			isCompleted: true,
			isAutomated: false,
			currentSubStep: -1,
			dealsWithSubFiles: true,
		},
		{
			step: 2,
			description: "",
			title: "Information Completeness",
			isCompleted: true,
			isAutomated: false,
			dealsWithSubFiles: false,
			currentSubStep: -1,
		},
		{
			step: 3,
			description: "",
			title: "Application Scorecard",
			isCompleted: false,
			isAutomated: true,
			dealsWithSubFiles: false,
			currentSubStep: 3,
			subSteps: [
				{
					step: 1,
					description: "Compute from extracted payslip & existing debt fields",
					title: "Debt-to-Income Ratio",
					isCompleted: false,
					isAutomated: true,
					dealsWithSubFiles: false,
					currentSubStep: -1,
				},
				{
					step: 2,
					description: "Appraised value vs. requested loan",
					title: "Validate LTV",
					isCompleted: false,
					isAutomated: true,
					dealsWithSubFiles: false,
					currentSubStep: -1,
				},
				{
					step: 3,
					description: "Cross-check declared vs. extracted income",
					title: "Fraud score",
					isCompleted: false,
					dealsWithSubFiles: false,
					isAutomated: true,
					currentSubStep: -1,
				},
				{
					step: 4,
					description: "Detect expired IDs or TCT encumbrances",
					title: "Red-flag alert",
					isCompleted: false,
					dealsWithSubFiles: false,
					isAutomated: true,
					currentSubStep: -1,
				},
			],
		},
		{
			step: 4,
			description: "",
			title: "Regulatory compliance",
			isCompleted: false,
			isAutomated: true,
			currentSubStep: 3,
			dealsWithSubFiles: false,
			subSteps: [
				{
					step: 1,
					description: "",
					title: "AMLA",
					isCompleted: false,
					dealsWithSubFiles: false,
					isAutomated: true,
					currentSubStep: -1,
				},
				{
					step: 2,
					description: "",
					title: "Real-Estate-Portfolio Limit Buffer",
					isCompleted: false,
					dealsWithSubFiles: false,
					isAutomated: true,
					currentSubStep: -1,
				},
			],
		},
		{
			step: 5,
			description: "",
			title: "Underwriter Review",
			isCompleted: false,
			dealsWithSubFiles: false,
			isAutomated: false,
			currentSubStep: 3,
		},
	],
};
